export const env = {
  NODE_ENV: process.env.NODE_ENV || 'development',
  PORT: Number(process.env.PORT) || 5000,
  HOST: process.env.HOST || (process.env.NODE_ENV === 'production' ? '127.0.0.1' : '0.0.0.0'),
  CLIENT_URL: process.env.CLIENT_URL || 'http://localhost:3000',
  API_URL: process.env.API_URL || 'http://localhost:5000/api/v1',
  MONGODB_URI: process.env.MONGODB_URI,
  JWT_SECRET: process.env.JWT_SECRET || 'dev_secret_change_me',
  JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN || '7d',
  JWT_COOKIE_EXPIRES_IN: Number(process.env.JWT_COOKIE_EXPIRES_IN || 7) * 24 * 60 * 60 * 1000,
  ADMIN_NAME: process.env.ADMIN_NAME || 'NOIR Admin',
  ADMIN_EMAIL: process.env.ADMIN_EMAIL || 'admin@noirsalon.in',
  ADMIN_PASSWORD: process.env.ADMIN_PASSWORD || 'ChangeMe123!',
  PAYMENT_PROVIDER: process.env.PAYMENT_PROVIDER || 'cash',
  UPI_ID: process.env.UPI_ID,
  UPI_BUSINESS_NAME: process.env.UPI_BUSINESS_NAME || 'NOIR SALON',
  UPI_MERCHANT_ID: process.env.UPI_MERCHANT_ID,
  UPI_CURRENCY: process.env.UPI_CURRENCY || 'INR',
  SMTP_HOST: process.env.SMTP_HOST,
  SMTP_PORT: Number(process.env.SMTP_PORT) || 587,
  SMTP_SECURE: process.env.SMTP_SECURE,
  SMTP_USER: process.env.SMTP_USER,
  SMTP_PASS: process.env.SMTP_PASS,
  MAIL_FROM: process.env.MAIL_FROM || 'NOIR SALON <no-reply@noirsalon.in>',
  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
  RAZORPAY_KEY_ID: process.env.RAZORPAY_KEY_ID,
  RAZORPAY_KEY_SECRET: process.env.RAZORPAY_KEY_SECRET,
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
  GOOGLE_PLACES_API_KEY: process.env.GOOGLE_PLACES_API_KEY,
  GOOGLE_MAP_EMBED: process.env.GOOGLE_MAP_EMBED,
  SALON_TIMEZONE: process.env.SALON_TIMEZONE || 'Asia/Kolkata',
  SALON_OPEN_TIME: process.env.SALON_OPEN_TIME || '10:00',
  SALON_CLOSE_TIME: process.env.SALON_CLOSE_TIME || '19:00',
  SALON_SLOT_INTERVAL_MINUTES: Number(process.env.SALON_SLOT_INTERVAL_MINUTES) || 30,
};
